### ISSUE TITLE
ignore or add external https fetch resource such as fonts and libraries store on a cdn

### ISSUE THREAD

**Issue by lv2lrn4lf** [oknagisa/html-inline-external#4]
I have this error here:

`[Error]: Unexpected Error [Error: ENOENT: no such file or directory,...`

it happens to cause an index.html I'm trying to compile as one resource to the server has an external resource that is stored in a CDN. How do you either make this tool fetch that resource or ignore those URL paths?

**Comment by rohan-salunke** [comment]
@lv2lrn4lf At this moment the script does not support CDN resources and should ignore resources by default, I reckon that path that you have entered must be incorrect, Can we have more info on how are you running the script and where is your file and resources located?

Ref: https://github.com/okrohan/html-inline-external/blob/master/src/html-inline-external.js#L32

**Comment by lv2lrn4lf** [comment]
okay @rohan-salunke can you request for a deletion of this post for me or delete it if you have the power... another post I have can you delete that one too, I put said it on tha post as well.

**Comment by okrohan** [comment]
@lv2lrn4lf do you want to close this thread?
